# -*- coding: utf-8 -*-
"""mlprojectfinal2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kFUYgH6wFTqwtdCwx9QmcgpQMhQC3fMD
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_curve, auc, roc_auc_score

import matplotlib.pyplot as plt

df = pd.read_csv("/content/How Ready Are You for Real-World Job Situations_  (Responses) - Form Responses 1.csv")
df.head()

df = df.iloc[:,2:]
df

for col in df.columns:
    unique_vals = df[col].unique()
    mapping = {val: i+1 for i, val in enumerate(unique_vals)}
    df[col] = df[col].map(mapping)

df.head()

X = df.iloc[:,0:8]
X

from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)

from sklearn.mixture import GaussianMixture
gmm = GaussianMixture(n_components=3, random_state=42)

gmm.fit(X_train)

# soft probabilities
train_prob = gmm.predict_proba(X_train)
test_prob = gmm.predict_proba(X_test)

# hard labels
y_train = np.argmax(train_prob, axis=1)
y_test = np.argmax(test_prob, axis=1)

cluster_means = gmm.means_.mean(axis=1)

sorted_idx = np.argsort(cluster_means)

mapping = {old: new for new, old in enumerate(sorted_idx)}

y_train = np.array([mapping[i] for i in y_train])
y_test = np.array([mapping[i] for i in y_test])

import pandas as pd

print("Train clusters:")
print(pd.Series(y_train).value_counts().sort_index())

print("\nTest clusters:")
print(pd.Series(y_test).value_counts().sort_index())

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

svm = SVC(kernel='rbf',
          C= 10 ,
          gamma = 0.5,
          probability = True,
          random_state = 42
          )
rf = RandomForestClassifier()
lr = LogisticRegression(C = 0.5)
knn = KNeighborsClassifier(n_neighbors=3)
dt = DecisionTreeClassifier(max_depth=3)
svm.fit(X_train, y_train)
rf.fit(X_train, y_train)
lr.fit(X_train, y_train)
knn.fit(X_train, y_train)
dt.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test ,y_pred, average='weighted')
recall = recall_score(y_test ,y_pred, average='weighted')
f1 = f1_score(y_test , y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test ,y_pred, average='weighted')
recall = recall_score(y_test ,y_pred, average='weighted')
f1 = f1_score(y_test , y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = lr.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test ,y_pred, average='weighted')
recall = recall_score(y_test ,y_pred, average='weighted')
f1 = f1_score(y_test , y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test ,y_pred, average='weighted')
recall = recall_score(y_test ,y_pred, average='weighted')
f1 = f1_score(y_test , y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = dt.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test ,y_pred, average='weighted')
recall = recall_score(y_test ,y_pred, average='weighted')
f1 = f1_score(y_test , y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_auc_score

# FIXED classes
classes = np.unique(y_train)

# binarize TRUE labels (NOT test_prob)
y_test_bin = label_binarize(y_test, classes=classes)

# model prediction
y_score = svm.predict_proba(X_test)

# AUC
auc_score = roc_auc_score(y_test_bin, y_score, average="macro")

print("AUC:", auc_score)

from sklearn.mixture import GaussianMixture

# GMM model
gmm = GaussianMixture(n_components=3, random_state=42)

# fit on full data (only for target creation)
gmm.fit(X)

# probabilities
prob = gmm.predict_proba(X)

# final labels (no formula)
y = np.argmax(prob, axis=1)

# store in dataframe
df['Risk_cluster'] = y
cluster_means = gmm.means_.mean(axis=1)

sorted_idx = np.argsort(cluster_means)

mapping = {old: new for new, old in enumerate(sorted_idx)}
centers = gmm.means_.mean(axis=1)

low = np.min(centers)
high = np.max(centers)

print("Low approx center:", low)
print("High approx center:", high)

df['Risk_cluster'] = df['Risk_cluster'].map(mapping)
print(df['Risk_cluster'].value_counts().sort_index())

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(6,6))

# micro-average ROC
fpr, tpr, _ = roc_curve(y_test_bin.ravel(), y_score.ravel())

roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label="ROC curve (AUC = %0.2f)" % roc_auc, linewidth=2)

plt.plot([0,1],[0,1],'k--', linewidth=1)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve (Micro-Average)")
plt.legend(loc="lower right")

plt.show()

new_data = np.array([[3,3,3,3,3,3,3,3]])

new_data = scaler.transform(new_data)

predicted_cluster = svm.predict(new_data)[0]

labels = {0: "Low Risk", 1: "Medium Risk", 2: "High Risk"}
print("Predicted Cluster:", predicted_cluster)
print("Predicted Level:", labels[predicted_cluster])

def risk_recommendation(predicted_cluster):
    base = ""
    recommendation = ""

    # Define base message and specific recommendations
    if predicted_cluster == 0:
        base = "You are not fully prepared for real-world job situations yet."
        recommendation = "To improve, actively seek out learning opportunities, engage in mock interviews, and participate in projects to gain practical experience. Embrace challenges as opportunities for growth."
    elif predicted_cluster == 1:
        base = "You are moderately prepared but need improvement in some areas."
        recommendation = "Focus on identifying specific areas where you lack confidence, such as asking clarifying questions when instructions are unclear or practicing structured problem-solving. Consider mentorship or targeted skill development."
    else:
        base = "You are fully prepared for real-world job situations."
        recommendation = "Continue to hone your skills, take on leadership roles, and mentor others. Explore advanced topics and continuously adapt to new challenges to maintain your edge."

    # Utilize risk_label in the final output (risk_label is defined in cell 55-mEJAuFdwr)
    return f"Based on your responses, your estimated risk level is {labels[predicted_cluster]}. {base} {recommendation}"

print("Predicted Risk Level:", predicted_cluster)
print(risk_recommendation(predicted_cluster))

from sklearn.mixture import GaussianMixture

bic_scores = []
k_values = range(1, 6)

for k in k_values:
    gmm = GaussianMixture(n_components=k, random_state=42)
    gmm.fit(X)
    bic_scores.append(gmm.bic(X))

# plot
import matplotlib.pyplot as plt

plt.plot(k_values, bic_scores, marker='o')
plt.xlabel("Number of Clusters")
plt.ylabel("BIC Score")
plt.title("BIC for GMM")
plt.show()

from sklearn.decomposition import PCA

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X)

from sklearn.decomposition import PCA

# PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# 🔥 GMM centers (means)
centroids = gmm.means_

# apply same mapping (low, medium, high)
centroids_corrected = np.zeros((3, centroids.shape[1]))

for old_label, new_label in mapping.items():
    centroids_corrected[new_label] = centroids[old_label]

# transform centroids to PCA space
centroids_pca = pca.transform(centroids_corrected)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

# data points
plt.scatter(X_pca[:,0], X_pca[:,1], c=df['Risk_cluster'], cmap='viridis')

# centroids
plt.scatter(
    centroids_pca[:,0],
    centroids_pca[:,1],
    c='black',
    s=200,
    label='Centers'
)

# labels
labels = ['Low', 'Medium', 'High']

for i in range(3):
    plt.text(
        centroids_pca[i,0],
        centroids_pca[i,1],
        labels[i],
        color='black',
        fontsize=10,
        ha='center'
    )

plt.title("GMM Clustering Visualization (PCA)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend()

plt.show()